version: '3.7'

services:
  input-receiver.service:
    image: thednp/wsevent:v0.2.1
    network_mode: container:input-receiver-proxy
    labels:
      svc: pseudopods
    environment:
      SERVE_ENDPOINT:     127.0.0.1:8080/events
      CONSUME_ENDPOINT:   192.168.57.10:10080/sensor-data
      NO_PRODUCE:         "true"
    deploy:
      restart_policy:
        condition: none
