version: '3.7'

x-deploy: 
  &common-deploy
  mode: replicated
  replicas: 3
  placement:
    preferences:
      - spread: type

services:
  dack-sender:
    image: ixdotai/swarm-launcher:latest
    entrypoint:
      - bash
    command:
      - -c
      - |-
        while true ; do 
          sleep 1 ;
          docker ps | grep $$PROXY && break ; 
        done;
        CONTAINER=$$(docker ps | grep $$PROXY | sed -re 's/.*\s//');
        sed -re "s/$$PROXY/$$CONTAINER/" \
            /tmp//docker-compose.tpl.yml > /docker-compose.yml;
        echo "++++++++++";
        /entrypoint.sh
    labels:
      svc: pseudopods
    environment:
      STACK: svc-pods--app
      LAUNCH_PROJECT_NAME:  pods-dack-sender
      PROXY: dack-sender-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    configs:
      - source: dack-sender.composefile
        target: /tmp/docker-compose.tpl.yml
    deploy: 
      << : *common-deploy
    networks: []
  dack-sender-proxy:
    image: nginx:latest
    deploy: 
      << : *common-deploy
    configs:
      - source: sidecar.dack-sender.proxy.conf
        target: /etc/nginx/conf.d/default.conf
    ports:
      - 10080:8081
    networks:
      - dack-net

configs:
  dack-sender.composefile:
    file: ./composefiles/app-dack-sender.yml
  sidecar.dack-sender.proxy.conf:
    file: ./sidecars/nginx.dack-sender.conf

networks:
  dack-net:
    name: "dack-net"
    external: true
