version: '3.7'

x-deploy: 
  &common-deploy
  mode: replicated
  replicas: 3
  placement:
    preferences:
      - spread: type

services:
  input-receiver:
    image: ixdotai/swarm-launcher:latest
    entrypoint:
      - bash
    command:
      - -c
      - |-
        while true ; do 
          sleep 1 ;
          docker ps | grep $$PROXY && break ; 
        done;
        CONTAINER=$$(docker ps | grep $$PROXY | sed -re 's/.*\s//');
        sed -re "s/$$PROXY/$$CONTAINER/" \
            /tmp//docker-compose.tpl.yml > /docker-compose.yml;
        echo "++++++++++";
        echo $$PROJECT
        /entrypoint.sh
    labels:
      svc: pseudopods
    environment:
      STACK: svc-pods--app
      LAUNCH_PROJECT_NAME:  pods-input-receiver
      PROXY: input-receiver-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    configs:
      - source: input-receiver.composefile
        target: /tmp/docker-compose.tpl.yml
    deploy: 
      << : *common-deploy
  input-receiver-proxy:
    image: nginx:latest
    deploy: 
      << : *common-deploy
    configs:
      - source: sidecar.input-receiver.proxy.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - dack-net

configs:
  input-receiver.composefile:
    file: ./composefiles/app-input-receiver.yml
  sidecar.input-receiver.proxy.conf:
    file: ./sidecars/nginx.input-receiver.conf

networks:
  dack-net:
    name: "dack-net"
    external: true
