version: '3.7'

services:
  debug:
    image: alpine/curl
    labels:
      svc: simple
    entrypoint: sh
    command:
      - "-c"
      - 'while true ; do sleep 3600 ; done'
    networks:
      - dack-net
    deploy:
      mode: replicated
      replicas: 3

#curl --no-buffer --header "Connection: Upgrade" --header "Upgrade: websocket" --header "Host: example.com:80" --header "Origin: http://example.com:80" --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ=="  -header "Sec-WebSocket-Version: 13" http://dacker:8080/dack-events

networks:
  dack-net:
    name: "dack-net"
    external: true
