version: '3.7'

services:
  network-init:
    labels:
      svc: simple
    image: hello-world
    configs:
      - source: sidecar.proxy.conf
        target: /tmp/sidecar.proxy.conf
    networks:
      - dack-net

configs:
  sidecar.proxy.conf:
    file: ./wsevent/svc-pseudopods/sidecars/nginx.conf


networks:
  dack-net:
    name: "dack-net"
    attachable: true
