version: '3.7'

services:
  dacker:
    image: ixdotai/swarm-launcher:latest
    entrypoint:
      - bash
    command:
      - -c
      - |-
        sed -re 's|location /events|location /dack-events|' /tmp/nginx.conf > /tmp/nginx.dacker.proxy.conf;
        /entrypoint.sh
    labels:
      svc: pseudopods
    environment:
      LAUNCH_PROJECT_NAME: pod-dacker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /tmp:/tmp
    configs:
      - source: dacker.composefile
        target: /docker-compose.yml
      - source: sidecar.proxy.conf
        target: /tmp/nginx.conf
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - dack-net

configs:
  dacker.composefile:
    file: ./wsevent/svc-pseudopods/composefiles/app-dacker.yml
  sidecar.proxy.conf:
    external: true
    name: svc-pseudopods--init_sidecar.proxy.conf

networks:
  dack-net:
    name: "dack-net"
    external: true
