version: '3.7'

services:
  input-receiver.service:
    image: thednp/wsevent:v0.2.1
    network_mode: container:input-receiver.proxy
    depends_on: 
      - input-receiver.proxy
    labels:
      svc: pseudopods
    environment:
      SERVE_ENDPOINT:     127.0.0.1:8080/events
      CONSUME_ENDPOINT:   192.168.57.10:10080/sensor-data
      NO_PRODUCE:         "true"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 2
        window: 30s
  input-receiver.proxy:
    container_name: input-receiver.proxy
    image: nginx:latest
    volumes:
      - type: bind
        source: /tmp/nginx.input-receiver.proxy.conf
        target: /etc/nginx/conf.d/default.conf
        bind:
          create_host_path: false
    networks:
      - dack-net

networks:
  dack-net:
    name: "dack-net"
    external: true
